---
name: act-mooc
delimiter: "\t"
files:
  - name: mooc_action_labels.tsv
    schema:
      - name: ACTIONID
        type: id
        extra:
          prefix: a
      - name: LABEL
        type: int
    facets:
      - entity: ACTIONID
        key: label
        value: LABEL
  - name: mooc_action_features.tsv
    schema:
      - name: ACTIONID
        type: id
        extra:
          prefix: a
      - name: FEATURE0
        type: float
      - name: FEATURE1
        type: float
      - name: FEATURE2
        type: float
      - name: FEATURE3
        type: float
    facets:
      - entity: ACTIONID
        key: feature0
        value: FEATURE0
      - entity: ACTIONID
        key: feature1
        value: FEATURE1
      - entity: ACTIONID
        key: feature2
        value: FEATURE2
      - entity: ACTIONID
        key: feature3
        value: FEATURE3
  - name: mooc_actions.tsv
    schema:
      - name: ACTIONID
        type: id
        extra:
          prefix: a
      - name: USERID
        type: id
        extra:
          prefix: u
      - name: TARGETID
        type: id
        extra:
          prefix: t
      - name: TIMESTAMP
        type: float
    facets:
      - entity: ACTIONID
        key: timestamp
        value: TIMESTAMP
    rdfs:
      - subject: USERID
        predicat: performs
        object: ACTIONID
        facet_entity: ACTIONID
      - subject: ACTIONID
        predicat: on
        object: TARGETID
